/**
 * Generated by chatGPT on 2024-10-05
 */

/**
 * Header Component Texts in Spanish
 */

const HEADER_TEXTS = {
    name: "Dheeraj",
    home: "Inicio",
    about: "Acerca de mí",
    work: "Experiencia",
    credential: "Credenciales",
    contact: "Contacto",
};

/**
 * Home Page Texts in Spanish
 */

const SKILLS = [
    "Salesforce",
    "Certinia (FinancialForce) PSA",
    "Gestión de Productos",
    "Análisis de Negocios",
    "Automatización",
    "Modelado de Datos",
    "Informes y Paneles",
    "Ágil y Scrum",
    "Estrategia de Pruebas y QA",
    "Gestión de Interesados",
    "Planificación de Hoja de Ruta",
];

const HOME_TEXTS = {
    profilePicAlt: "Foto del Dr. Dheeraj Panday",
    greeting: "¡HOLA!",
    intro1: "SOY",
    intro2: "DHEERAJ",
    role: "Gerente de Producto / Consultor de Salesforce PSA / Analista de Negocios",
    description:
        "Soy un Consultor de Salesforce y Certinia (FinancialForce) PSA con más de 18 años de experiencia en gestión de productos, estrategia de QA y análisis de datos. Me especializo en definir hojas de ruta de producto, implementar soluciones PSA y lograr resultados empresariales basados en datos.",
    coreSkills: "Habilidades Principales",
    skills: SKILLS,
};

/**
 * About Me Section in Spanish
 */

const ABOUT_ME = [
    "Soy el Dr. Dheeraj Panday, un Gerente de Producto y Consultor de Salesforce PSA con más de 18 años de experiencia en gestión de productos, consultoría, control de calidad (QA) y análisis de datos. Mi experiencia se centra en implementaciones de Salesforce y Certinia (FinancialForce) PSA, donde he entregado soluciones que mejoran la eficiencia operativa y la rentabilidad.",
    "En Metacube Software, he liderado múltiples iniciativas de producto para Certinia: definiendo y ejecutando hojas de ruta de producto, dirigiendo ceremonias ágiles, gestionando lanzamientos y colaborando con equipos multifuncionales para ofrecer características con alto impacto.",
    "Mi carrera profesional comenzó como Analista de Datos, evolucionó hacia QA y consultoría PSA en Salesforce, y posteriormente hacia la gestión de productos. Durante este tiempo, he desarrollado una base sólida en modelado de datos, estrategia de pruebas, propiedad de producto y diseño centrado en el cliente.",
    "Poseo un Doctorado (Ph.D.) en Contabilidad y Estadística Empresarial, y una Maestría en Aplicaciones Informáticas. Me apasiona guiar equipos, innovar en estrategia de productos y ayudar a las organizaciones a lograr resultados medibles mediante Salesforce PSA.",
];

const ABOUT_ME_TEXTS = {
    aboutMeHeading: "Acerca de Mí",
    aboutMeParagraphs: ABOUT_ME,
};

/**
 * Work Experience Section in Spanish
 */

const WORK_EXPERIENCES = [
    {
        company: "Metacube Software Pvt. Ltd.",
        role: "Gerente de Producto | Cliente – Certinia (anteriormente FinancialForce)",
        duration: "Junio 2006 – Presente",
        responsibilities: [
            "Definir, priorizar y entregar hojas de ruta de producto alineadas con los objetivos de negocio de Certinia.",
            "Colaborar con equipos multifuncionales para diseñar e implementar características de alto impacto.",
            "Redactar PRDs, historias de usuario y métricas de éxito para nuevas funciones y su adopción.",
            "Liderar ceremonias ágiles y gestionar el ciclo de vida completo del producto, desde la idea hasta el lanzamiento.",
            "Realizar análisis de competencia y tendencias para impulsar la innovación del producto y mejorar la experiencia del cliente.",
            "Apoyar la planificación de lanzamientos, la formación de usuarios y la adopción de PSA.",
        ],
    },
    {
        company: "Metacube Software Pvt. Ltd.",
        role: "Consultor PSA / Salesforce | Cliente – Certinia (anteriormente FinancialForce)",
        duration: "Junio 2015 – Marzo 2020",
        responsibilities: [
            "Implementar y configurar módulos PSA, incluidos Proyectos, Gestión de Recursos, Facturación y Reconocimiento de Ingresos.",
            "Personalizar automatizaciones, flujos de trabajo y aprobaciones en Salesforce según los requisitos del negocio.",
            "Desarrollar paneles ejecutivos y análisis para decisiones basadas en datos.",
            "Dirigir UAT, validaciones del sistema y formación de usuarios finales para garantizar precisión y adopción.",
            "Mejorar la utilización de recursos y la rentabilidad de proyectos mediante optimizaciones basadas en PSA.",
        ],
    },
    {
        company: "Metacube Software Pvt. Ltd.",
        role: "Líder QA / Consultor PSA | Cliente – Certinia (anteriormente FinancialForce)",
        duration: "Septiembre 2012 – Mayo 2015",
        responsibilities: [
            "Dirigir la estrategia de QA y la automatización para implementaciones de PSA en varios módulos.",
            "Diseñar y ejecutar pruebas de regresión y funcionales para garantizar estabilidad en los lanzamientos.",
            "Validar configuraciones y flujos de PSA para mejorar la calidad y reducir defectos.",
            "Colaborar con clientes y propietarios de producto para validar los procesos empresariales de extremo a extremo.",
        ],
    },
    {
        company: "Metacube Software Pvt. Ltd.",
        role: "QA de Salesforce | Cliente – Certinia (anteriormente FinancialForce)",
        duration: "Octubre 2010 – Agosto 2012",
        responsibilities: [
            "Crear y ejecutar casos de prueba de regresión e integración para Salesforce + PSA.",
            "Validar flujos de trabajo, objetos y configuraciones de lógica empresarial.",
            "Realizar pruebas de validación y migración de datos durante los ciclos de implementación.",
        ],
    },
    {
        company: "Metacube Software Pvt. Ltd.",
        role: "Analista de Datos | Cliente – NPD Group (anteriormente Current Analysis West)",
        duration: "Junio 2006 – Septiembre 2010",
        responsibilities: [
            "Realizar análisis de mercado y precios para el sector de Impresoras y Suministros de EE.UU.",
            "Construir modelos de datos y herramientas de previsión para identificar tendencias del sector.",
            "Entregar informes e ideas accionables para respaldar decisiones de producto y marketing.",
        ],
    },
];

const WORK_EXPERIENCE_TEXTS = {
    workExperienceHeading: "Experiencia Profesional",
    workExperiences: WORK_EXPERIENCES,
};

/**
 * Credentials Section in Spanish
 */

const CERTIFICATIONS = [
    "Salesforce Certified AI Associate",
    "Salesforce Certified Agentforce Specialist",
    "Salesforce Certified Platform Administrator",
    "Salesforce Certified Business Analyst",
];

const EDUCATIONS = [
    {
        degree: "Doctorado (Ph.D.) en Contabilidad y Estadística Empresarial",
        additionalInfo: "2019 | Universidad de Rajastán",
    },
    {
        degree: "Maestría en Aplicaciones Informáticas (MCA)",
        additionalInfo: "2009 | Universidad de Rajastán",
    },
];

const PROJECTS = [
    {
        name: "Mejoras de Certinia PSA",
        description:
            "Dirigió mejoras continuas en los módulos de PSA, mejorando la gestión de recursos, la visibilidad de proyectos y la precisión de facturación mediante automatización y análisis.",
        skills: "Salesforce | Certinia PSA | Gestión de Productos | Ágil | Analítica",
    },
    {
        name: "Marco de Automatización QA para Salesforce",
        description:
            "Desarrolló conjuntos de regresión y automatización reutilizables para mejorar la calidad de los lanzamientos y reducir defectos en múltiples productos PSA.",
        skills: "Salesforce | Automatización | Estrategia de Pruebas | Gestión de QA",
    },
    {
        name: "Plataforma de Análisis de Datos del Mercado",
        description:
            "Desarrolló paneles y modelos analíticos para pronósticos de tendencias de mercado e informes ejecutivos.",
        skills: "Modelado de Datos | BI | Informes | Analítica",
    },
];

const CREDENTIAL_TEXTS = {
    credentialHeading: "Credenciales",
    certificationsHeading: "Certificaciones",
    educationsHeading: "Educación",
    projectsHeading: "Proyectos Destacados",
    certifications: CERTIFICATIONS,
    educations: EDUCATIONS,
    projects: PROJECTS,
};

/**
 * Contact Section in Spanish
 */

const CONTACT_TEXTS = {
    contactHeading: "Ponte en Contacto",
    contactDescription:
        "Siempre estoy abierto a conversaciones sobre Salesforce PSA, estrategia de producto u oportunidades de consultoría. No dudes en ponerte en contacto para colaborar o compartir conocimientos.",
    email: "Correo electrónico",
    emailAddress: "consultantpsa419@gmail.com",
    socialProfiles: "Perfiles Sociales",
    githubLink: "https://github.com/drdheerajpanday66-code",
    linkedInLink: "https://www.linkedin.com/in/dr-dheeraj-panday-6a8b4221/",
    trailheadLink: "https://www.salesforce.com/trailblazer/dpandey2",
    emailMe: "Envíame un correo",
    linkedIn: "LinkedIn",
    downloadResume: "Descargar Currículum",
};

/**
 * Footer Component Texts in Spanish
 */

const FOOTER_TEXTS = {
    copyright: "© 2025 Dr. Dheeraj Panday. Todos los derechos reservados.",
};

export {
    HEADER_TEXTS,
    HOME_TEXTS,
    ABOUT_ME_TEXTS,
    WORK_EXPERIENCE_TEXTS,
    CREDENTIAL_TEXTS,
    CONTACT_TEXTS,
    FOOTER_TEXTS,
};
