/**
 * Generated by chatGPT on 2024-10-05
 */

import aiAssociate from "../../assets/certificates/sf-AIAssociate.pdf";
import aiSpecialist from "../../assets/certificates/sf-agentforceSpecialist.pdf";
import businessAnalyst from "../../assets/certificates/sf-businessAnalyst.pdf";
import administrator from "../../assets/certificates/sf-administrator.pdf";

/**
 * Header Component Texts in Hindi
 */

const HEADER_TEXTS = {
    name: "धीरेज",
    home: "होम",
    about: "परिचय",
    work: "अनुभव",
    credential: "प्रमाणपत्र",
    contact: "संपर्क",
};

/**
 * Home Page Texts in Hindi
 */

const SKILLS = [
    "Salesforce",
    "Certinia (FinancialForce) PSA",
    "प्रोडक्ट मैनेजमेंट",
    "बिज़नेस एनालिसिस",
    "ऑटोमेशन",
    "डेटा मॉडलिंग",
    "रिपोर्ट्स और डैशबोर्ड्स",
    "एजाइल और स्क्रम",
    "टेस्ट स्ट्रैटेजी और QA",
    "स्टेकहोल्डर मैनेजमेंट",
    "रोडमैप प्लानिंग",
];

const HOME_TEXTS = {
    profilePicAlt: "डॉ. धीरेज पांडे का चित्र",
    greeting: "नमस्ते!",
    intro1: "मैं हूँ",
    intro2: "धीरेज",
    role: "प्रोडक्ट मैनेजर / Salesforce PSA कंसल्टेंट / बिज़नेस एनालिस्ट",
    description:
        "मैं Salesforce और Certinia (FinancialForce) PSA कंसल्टेंट हूँ, जिसके पास प्रोडक्ट मैनेजमेंट, QA स्ट्रैटेजी और डेटा एनालिटिक्स में 18+ वर्षों का अनुभव है। मैं प्रोडक्ट रोडमैप तैयार करने, PSA सॉल्यूशंस लागू करने और डेटा-आधारित निर्णयों के माध्यम से व्यवसायिक परिणाम प्राप्त करने में विशेषज्ञ हूँ।",
    coreSkills: "मुख्य कौशल",
    skills: SKILLS,
};

/**
 * About Me Section in Hindi
 */

const ABOUT_ME = [
    "मैं डॉ. धीरेज पांडे हूँ — एक प्रोडक्ट मैनेजर और Salesforce PSA कंसल्टेंट, जिसके पास प्रोडक्ट मैनेजमेंट, कंसल्टिंग, QA और डेटा एनालिसिस में 18 से अधिक वर्षों का अनुभव है। मेरी विशेषज्ञता Salesforce और Certinia (FinancialForce) PSA इम्प्लीमेंटेशन में है, जहाँ मैंने दक्षता और लाभप्रदता बढ़ाने वाले समाधान सफलतापूर्वक प्रदान किए हैं।",
    "Metacube Software में, मैंने Certinia के लिए कई प्रोडक्ट इनिशिएटिव्स का नेतृत्व किया है — जिनमें प्रोडक्ट रोडमैप की योजना, एजाइल सेरेमनीज़ का संचालन, रिलीज़ मैनेजमेंट और क्रॉस-फंक्शनल टीमों के साथ सहयोग शामिल है।",
    "मेरी प्रोफेशनल यात्रा डेटा एनालिस्ट के रूप में शुरू हुई, उसके बाद Salesforce QA और PSA कंसल्टिंग में अनुभव प्राप्त किया और अब मैं प्रोडक्ट मैनेजमेंट में नेतृत्व की भूमिका निभा रहा हूँ। इस दौरान मैंने डेटा मॉडलिंग, टेस्ट स्ट्रैटेजी, प्रोडक्ट ओनरशिप और कस्टमर-सेंट्रिक डिज़ाइन में मज़बूत नींव बनाई है।",
    "मैंने अकाउंटेंसी और बिज़नेस स्टैटिस्टिक्स में पीएच.डी. और कंप्यूटर एप्लीकेशंस में मास्टर की डिग्री प्राप्त की है। मैं टीमों को मार्गदर्शन देने, प्रोडक्ट स्ट्रैटेजी में नवाचार लाने और संगठनों को मापने योग्य परिणाम देने के लिए प्रेरित हूँ।",
];

const ABOUT_ME_TEXTS = {
    aboutMeHeading: "मेरे बारे में",
    aboutMeParagraphs: ABOUT_ME,
};

/**
 * Work Experience Section in Hindi
 */

const WORK_EXPERIENCES = [
    {
        company: "Metacube Software Pvt. Ltd.",
        role: "प्रोडक्ट मैनेजर | क्लाइंट – Certinia (पूर्व में FinancialForce)",
        duration: "जून 2006 – वर्तमान",
        responsibilities: [
            "Certinia के व्यावसायिक लक्ष्यों के अनुरूप प्रोडक्ट रोडमैप तैयार करना और डिलीवर करना।",
            "क्रॉस-फंक्शनल टीमों के साथ मिलकर उच्च-प्रभाव वाले प्रोडक्ट फीचर्स डिजाइन और लागू करना।",
            "PRD, यूज़र स्टोरीज़ और सफलता के मेट्रिक्स तैयार करना।",
            "एजाइल सेरेमनीज़ का नेतृत्व करना और विचार से रिलीज़ तक प्रोडक्ट लाइफसाइकिल संभालना।",
            "प्रतिस्पर्धा और बाज़ार प्रवृत्तियों का विश्लेषण करके नवाचार और ग्राहक अनुभव को बढ़ाना।",
            "रिलीज़ प्लानिंग, यूज़र ट्रेनिंग और PSA अपनाने में सहायता प्रदान करना।",
        ],
    },
    {
        company: "Metacube Software Pvt. Ltd.",
        role: "PSA / Salesforce कंसल्टेंट | क्लाइंट – Certinia (पूर्व में FinancialForce)",
        duration: "जून 2015 – मार्च 2020",
        responsibilities: [
            "PSA मॉड्यूल्स (Projects, Resource Management, Billing, Revenue Recognition) का इम्प्लीमेंटेशन और कॉन्फ़िगरेशन किया।",
            "Salesforce ऑटोमेशन, वर्कफ़्लो और अप्रूवल प्रोसेसेज़ को व्यवसायिक आवश्यकताओं के अनुसार कस्टमाइज़ किया।",
            "एक्ज़ीक्यूटिव डैशबोर्ड्स और एनालिटिक्स विकसित किए ताकि डेटा-आधारित निर्णय लिए जा सकें।",
            "UAT, सिस्टम वैलिडेशन और यूज़र ट्रेनिंग का संचालन किया ताकि सटीकता और अपनाने की दर बढ़ाई जा सके।",
            "PSA आधारित अनुकूलन के माध्यम से संसाधन उपयोग और प्रोजेक्ट लाभप्रदता को बढ़ाया।",
        ],
    },
    {
        company: "Metacube Software Pvt. Ltd.",
        role: "Salesforce लीड QA / PSA कंसल्टेंट | क्लाइंट – Certinia (पूर्व में FinancialForce)",
        duration: "सितंबर 2012 – मई 2015",
        responsibilities: [
            "PSA इम्प्लीमेंटेशन के लिए QA रणनीति और ऑटोमेशन का नेतृत्व किया।",
            "रीग्रेशन और फंक्शनल टेस्ट सूट्स को डिज़ाइन और निष्पादित किया ताकि रिलीज़ स्थिर रहे।",
            "PSA कॉन्फ़िगरेशन और वर्कफ़्लो को सत्यापित किया, गुणवत्ता में सुधार किया और डिफेक्ट्स को कम किया।",
            "क्लाइंट्स और प्रोडक्ट ओनर्स के साथ सहयोग करके व्यवसायिक वर्कफ़्लो को सत्यापित किया।",
        ],
    },
    {
        company: "Metacube Software Pvt. Ltd.",
        role: "Salesforce QA | क्लाइंट – Certinia (पूर्व में FinancialForce)",
        duration: "अक्टूबर 2010 – अगस्त 2012",
        responsibilities: [
            "Salesforce + PSA के लिए रीग्रेशन और इंटीग्रेशन टेस्ट केस तैयार किए और निष्पादित किए।",
            "वर्कफ़्लो, ऑब्जेक्ट्स और बिज़नेस लॉजिक कॉन्फ़िगरेशन का सत्यापन किया।",
            "इम्प्लीमेंटेशन चक्रों के दौरान डेटा वैलिडेशन और माइग्रेशन टेस्टिंग की।",
        ],
    },
    {
        company: "Metacube Software Pvt. Ltd.",
        role: "डेटा एनालिस्ट | क्लाइंट – NPD Group (पूर्व में Current Analysis West)",
        duration: "जून 2006 – सितंबर 2010",
        responsibilities: [
            "US प्रिंटिंग और सप्लाईज़ डोमेन के लिए मार्केट और प्राइस एनालिसिस किया।",
            "ट्रेंड्स की पहचान के लिए डेटा मॉडल्स और फोरकास्टिंग टूल्स तैयार किए।",
            "प्रोडक्ट और मार्केटिंग निर्णयों का समर्थन करने वाली इनसाइट्स और रिपोर्ट्स तैयार कीं।",
        ],
    },
];

const WORK_EXPERIENCE_TEXTS = {
    workExperienceHeading: "व्यावसायिक अनुभव",
    workExperiences: WORK_EXPERIENCES,
};

/**
 * Credentials Section in Hindi
 */

const CERTIFICATIONS = [
    {
        name: "Salesforce सर्टिफाइड AI एसोसिएट",
        link: aiAssociate,
    },
    {
        name: "Salesforce सर्टिफाइड Agentforce स्पेशलिस्ट",
        link: aiSpecialist,
    },
    {
        name: "Salesforce सर्टिफाइड प्लेटफॉर्म एडमिनिस्ट्रेटर",
        link: administrator,
    },
    { name: "Salesforce सर्टिफाइड बिज़नेस एनालिस्ट", link: businessAnalyst },
];

const EDUCATIONS = [
    {
        degree: "डॉक्टर ऑफ फिलॉसफी (Ph.D.) इन अकाउंटेंसी एंड बिज़नेस स्टैटिस्टिक्स",
        additionalInfo: "2019 | राजस्थान विश्वविद्यालय",
    },
    {
        degree: "मास्टर ऑफ कंप्यूटर एप्लीकेशंस (MCA)",
        additionalInfo: "2009 | राजस्थान विश्वविद्यालय",
    },
];

const PROJECTS = [
    {
        name: "Certinia PSA सुधार",
        description:
            "PSA मॉड्यूल्स में निरंतर उत्पाद सुधारों का नेतृत्व किया — जिससे संसाधन प्रबंधन, प्रोजेक्ट दृश्यता और बिलिंग सटीकता में वृद्धि हुई।",
        skills: "Salesforce | Certinia PSA | प्रोडक्ट मैनेजमेंट | एजाइल | एनालिटिक्स",
    },
    {
        name: "Salesforce QA ऑटोमेशन फ्रेमवर्क",
        description:
            "PSA प्रोडक्ट्स में रिलीज़ क्वालिटी सुधारने और डिफेक्ट्स कम करने के लिए पुन: प्रयोज्य रीग्रेशन और टेस्ट ऑटोमेशन सूट विकसित किए।",
        skills: "Salesforce | ऑटोमेशन | टेस्ट स्ट्रैटेजी | QA मैनेजमेंट",
    },
    {
        name: "मार्केट डेटा एनालिटिक्स प्लेटफॉर्म",
        description:
            "मार्केट ट्रेंड पूर्वानुमान और एक्ज़ीक्यूटिव रिपोर्टिंग के लिए एनालिटिकल डैशबोर्ड्स और मॉडल विकसित किए।",
        skills: "डेटा मॉडलिंग | BI | रिपोर्टिंग | एनालिटिक्स",
    },
];

const CREDENTIAL_TEXTS = {
    credentialHeading: "प्रमाणपत्र",
    certificationsHeading: "प्रमाणपत्र",
    educationsHeading: "शिक्षा",
    projectsHeading: "मुख्य प्रोजेक्ट्स",
    certifications: CERTIFICATIONS,
    educations: EDUCATIONS,
    projects: PROJECTS,
};

/**
 * Contact Section in Hindi
 */

const CONTACT_TEXTS = {
    contactHeading: "संपर्क करें",
    contactDescription:
        "मैं हमेशा Salesforce PSA, प्रोडक्ट स्ट्रैटेजी या कंसल्टिंग अवसरों पर चर्चा के लिए तैयार हूँ। सहयोग या ज्ञान साझा करने के लिए बेझिझक संपर्क करें।",
    email: "ईमेल",
    emailAddress: "consultantpsa419@gmail.com",
    socialProfiles: "सोशल प्रोफाइल्स",
    githubLink: "https://github.com/drdheerajpanday66-code",
    linkedInLink: "https://www.linkedin.com/in/dr-dheeraj-panday-6a8b4221/",
    trailheadLink: "https://www.salesforce.com/trailblazer/dpandey2",
    emailMe: "मुझे ईमेल करें",
    linkedIn: "लिंक्डइन",
    downloadResume: "रिज़्यूमे डाउनलोड करें",
};

/**
 * Footer Component Texts in Hindi
 */

const FOOTER_TEXTS = {
    copyright: "© 2025 डॉ. धीरेज पांडे. सर्वाधिकार सुरक्षित।",
};

export {
    HEADER_TEXTS,
    HOME_TEXTS,
    ABOUT_ME_TEXTS,
    WORK_EXPERIENCE_TEXTS,
    CREDENTIAL_TEXTS,
    CONTACT_TEXTS,
    FOOTER_TEXTS,
};
